spring.application.name=url-shortener
spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener
spring.datasource.password=password
spring.datasource.username=postgres
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
security.jwt.secret-key=617040da3b64e89bb7641a4aba175423a065e1d657b8302ede0ea0d32cacc8a569208ba6968618ebb56e6991c85fdd6c29fc10cd53a96f40707fe00188f9578d
security.jwt.expiration-duration=1000*60*3;
spring.web.resources.add-mappings=false
logging.level.org.springframework.security=debug
